# Generated by Django 3.0.6 on 2020-06-04 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_is_facorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='is_facorite',
            new_name='is_favorite',
        ),
    ]
